x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  acs-grader:
    image: ghcr.io/nxdus/acs-grader:0.1-c
    env_file: .env
    # ports:
    #   - "3000:3000"
    depends_on:
      - app-postgres
      - judge0-server
    <<: *default-logging
    restart: always
    networks:
      - dokploy-network

  app-postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: ${APP_POSTGRES_DB}
      POSTGRES_USER: ${APP_POSTGRES_USER}
      POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD}
    volumes:
      - app-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always
    networks:
      - dokploy-network

  judge0-server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always
    networks:
      - dokploy-network

  judge0-workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    networks:
      - dokploy-network

  judge0-postgres:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - judge0-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always
    networks:
      - dokploy-network

  judge0-redis:
    image: redis:7.2.4
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always
    networks:
      - dokploy-network

volumes:
  judge0-data:
  app-data:

networks:
  dokploy-network:
    external: true
