-- AlterEnum
ALTER TYPE "SubmissionStatus" ADD VALUE 'INTERNAL_ERROR';
ALTER TYPE "SubmissionStatus" ADD VALUE 'EXEC_FORMAT_ERROR';
ALTER TYPE "SubmissionStatus" ADD VALUE 'MEMORY_LIMIT_EXCEEDED';
ALTER TYPE "SubmissionStatus" ADD VALUE 'OUTPUT_LIMIT_EXCEEDED';
ALTER TYPE "SubmissionStatus" ADD VALUE 'STORAGE_LIMIT_EXCEEDED';
